import type { dictType } from "../types";

export const nameDict: dictType = {
    "name": "nombres",
    "type": "enum",
    "options":{
        "Carolina": ["caro", "caroulin", "carolina"],


        "Nicol": ["nicki", "nikki", "niki"],
        
        "Martina": ["martu"],
        
        "Benjamín": ["benja"],
        
        "Luciano": ["lucho"],
        
        "Agustín": ["agus"],
        
        "Oscar": ["oski"],
        
        "Adriana": ["adri"],
        "Lautaro": ["lauti", "taro"],
        
        "Brian": ["bri", "briancho"],
        "Brayan": ["bray", "brayanton", "brayi"],
        "Brenda": ["bren", "brendi"],
        "Axel": ["axe", "ax"],
        "Micaela": ["mica", "miki"],
        
        "Delfina": ["delfi", "fina"],
        
        "Lucas": ["lucas", "luquitas"],
        
        
        "Gustavo": ["tavo", "gus"],
        "Alan": ["alancito", "alancho"],
        "Ariel": ["ari", "arielito"],
        "Omar": ["omarcito", "omarito"],
        "Romina": ["romi", "rominita"],
        "Susana": ["susi", "susanita"],
        "Candelaria": ["cande", "candela"],
        "Simón": ["simoncito", "simi"],
        "Damián": ["dami", "dame"],
        "Néstor": ["nes", "nestorcito"],
        "Hernán": ["nano", "her"],
        "Grasiela": ["grasi", "grasiela"],
        "Luciana": ["luchu", "luchita"],
        "Abril": ["abri", "abrilita"],
        "Antonella": ["antona", "antonella"],
        "Milagros": ["mili", "milas"],
        "Yamila": ["yami", "yamila"],
        "Melina": ["meli", "mel"],
        "Aldana": ["aldanita", "dana"],
        "Celeste": ["cele", "celes"],
        "Érica": ["eri", "eric"],
        "Samanta": ["sami", "sam"],
        "Tamara": ["tami", "tam"],
        "Gino": ["ginito", "gi"],
        "Ciro": ["ciru", "cirilo"],
        "Mario": ["marito", "mari"],
        "Cristóbal": ["cris", "cristo"],
        "Gregorio": ["grego", "goyo"],
        "Dante": ["danti", "dantecito"],
        "Ismael": ["isma", "ismi"],
        "Baltasar": ["baltas", "balti"],
        "Lorenzo": ["lenzo", "loren"],
        "William": ["willi", "wuilli", "wlli"],
        "Willian": ["williannn"],
        "Wiliam": ["wili", "wuili"],
        "Wilian": ["wiliann"],

        "Aldo": ["aldito", "aldín"],
        "Amador": ["amad", "amadorcito"],
        "Aníbal": ["aní", "balito"],
        "Armando": ["arman", "mandito"],
        "Azucena": ["azus", "cena"],
        "Amparo": ["ampa", "paro"],
        "Asunción": ["asun", "chon"],
        "Aroa": ["aro", "aroa"],
        "Aina": ["aini", "ainita"],
        "Abigaíl": ["abi", "abigail"],
        "Gaston": ["gasty", "gastucho"],
        "Adrián": ["adri", "rian"],
        "Alba": ["albi", "albita"],
        "Alberto": ["beto", "alber"],
        "Alejandra": ["ale", "jandra"],
        "Alejandro": ["jandro", "alex"],
        "Alicia": ["lici", "licha"],
        "Alonso": ["onso", "alonsito"],
        "Amalia": ["mali", "amalita"],
        "Ana": ["anita", "ani"],
        "Andrés": ["andy", "dres"],
        "André": ["andreh", "andre"],
        "Ángel": ["angelito", "gel", "angel"],
        "Antonia": ["toni", "tonita"],
        "Antonio": ["tonio", "toño"],
        "Araceli": ["ara", "celi"],
        "Arturo": ["turo", "arturito"],
        "Aurora": ["auro", "rora"],
        "Amadeo": ["amade", "deo"],
        "Aarón": ["aroncito", "aaron"],
        "Agostina": ["agos", "tina"],
        "Anabel": ["ana", "bel"],
        "Annabel": ["anna"],
        "Anacleto": ["cleto", "anac"],
        "Arnaldo": ["arna", "naldo"],
        "Arnold": ["Arni", "arnol"],
        
        "Beatriz": ["bea", "triz"],
        "Berta": ["berti", "bertita"],
        "Blanca": ["blanqui", "blanquita"],
        "Bruno": ["bru", "brunito"],
        "Bárbara": ["barbi", "barbarita"],
        "Bayron": ["Bay"],
        "Bairon": ["Bairon"],
        "Belén": ["bele", "belu"],
        "Benito": ["beni", "bencho"],
        "Bernardino": ["bernard", "dino"],
        "Bautista": ["bauti", "taista"],
        "Brigida": ["brigi", "gida"],
        "Blas": ["blasito", "blasi"],
        "Basilio": ["basi", "silio"],
        "Bernardo": ["berna", "nardito"],
        "Benicio": ["beni", "nicio"],
        "Brandon": ["bran", "brandin"],

        "Candelario": ["lario"],
        "Candela": ["cande"],
        "Claudio": ["clau", "claudito"],
        "Camila": ["cami", "mila"],
        "Carlos": ["carlitos", "charli"],
        "Carmen": ["carmencita", "menchu"],
        "Carola": ["carol"],
        "Carla": ["car", "carli"],
        "Camilo": ["milo"],
        "Catalina": ["cata", "catali"],
        "Cecilia": ["ceci", "cecita"],
        "Celia": ["celi", "celita"],
        "Clara": ["clari", "clarita"],
        "Claudia": ["clau", "claudita"],
        "Concepción": ["conchi", "conchita"],
        "Cristina": ["cristina"],
        "Cristian": ["cristian"],
        "Cristofer": ["Cristof", "Cristo"],
        "César": ["cesarito", "sesa"],
        "Cirilo": ["ciri", "rilo"],
        "Crisanto": ["crisan", "santo"],
        "Cruz": ["crucita", "cruzi"],
        "Celestino": ["celes", "tino"],
        "Clemente": ["clemen", "mento"],
        "Consuelo": ["consu", "suelo"],
        "Priscila": ["pri"],
        "Elizabeth": ["elizabet", "beth", "elisabeth"],
        

        "Dacio": ["dacito", "daci"],
        "Dámaso": ["dama", "masito"],
        "Demetrio": ["deme", "metrio"],
        "Donato": ["don", "donatito"],
        "Dorotea": ["doro", "teita"],
        "Daniel": ["dan", "danielito"],
        "Dayana": ["daya"],
        "Dayara": ["dayar"],
        "Dayra": ["day"],
        "Daira": ["dai"],
        "Daiana": ["daiana", "daianita"],
        "Daniela": ["dani", "danita"],
        "David": ["davi", "davidcito"],
        "Diana": ["didi", "dianita"],
        "Diego": ["dieguito", "diegote"],
        "Dolores": ["lola", "lolita"],
        "Damian": ["Dami", "Damiansito"],
        "Dardo": ["dardi", "dardito"],
        "Débora": ["debi", "bora"],
        "Diamela": ["diame", "mela"],
        "Dionisio": ["dioni", "nisio"],
        "Dorila": ["dori", "rila"],
        
        "Edgar": ["ed", "edgarcito"],
        "Elena": ["elenita", "lele"],
        "Eliana": ["eli", "eliana"],
        "Elsa": ["elsita", "elsi"],
        "Emilia": ["emi", "emilita"],
        "Enrique": ["quique", "enri"],
        "Ernesto": ["neto", "ernestito"],
        "Esperanza": ["esper", "pera"],
        "Esteban": ["este", "teban"],
        "Eva": ["evita", "evi"],
        "Emiliano": ["emi", "miliano"],
        "Enzo": ["enzito", "enzo"],
        "Ezequiel": ["eze", "zeke"],
        "Elías": ["eliasito", "elias"],
        "Eduardo": ["eddie", "lalo"],
        "Emanuel": ["manu", "ema"],
        "Efraín": ["efra", "frai"],
        "Eladio": ["elad", "ladio"],
        "Mayra": ["may", "mayrita"],
        
        "Fabián": ["fabi", "fabo"],
        "Fabiola": ["fabi", "fiola"],
        "Federico": ["fede", "federi"],
        "Felipe": ["feli", "pipe"],
        "Fernanda": ["fer", "nanda"],
        "Fernando": ["fer", "nando"],
        "Francisco": ["paco", "pancho"],
        "Francisca": ["franci", "cisca"],
        "Florencia": ["flore", "floren"],
        "Flor": ["florsi", "flr", "for"],
        "Facundo": ["facu", "facus"],
        "Fermín": ["fermi", "mincho"],
        "Fidel": ["fidelito", "fide"],
        "Florencio": ["flor", "rencio"],
        "Franco": ["fran", "franquito", "fran", "franky", "franki"],
        "Fabricio": ["fabri", "fabro"],
        "Fausto": ["faus", "faustito"],
        
        "Gabriel": ["gabo", "gabrielito"],
        "Gabriela": ["gabi", "gabita"],
        "Gerardo": ["gera", "gerry"],
        "Germán": ["germanito", "manín"],
        "Gloria": ["glori", "glorita"],
        "Gonzalo": ["gonza", "gonzalo"],
        "Guadalupe": ["lupe", "lupita"],
        "Guillermo": ["memo", "guille", "guillermito", "gille", "guille"],
        
        "Héctor": ["hectorcito", "tor", "hector", "ector"],
        "Helena": ["helenita", "lena"],
        "Horacio": ["hora", "racio"],
        "Hugo": ["huguito", "hugón"],
        
        "Ignacio": ["nacho", "ignacio"],
        "Iker": ["ike", "ikerito"],
        "Inés": ["inesita", "nesi"],
        "Irene": ["ire", "irenita"],
        "Isabel": ["isa", "bel"],
        "Isabella": ["bella", "isa"],
        "Israel": ["isra", "rael"],
        "Iván": ["ivancito", "ivancho"],
        "Inocencio": ["inocen", "cencio"],
        "Indalecio": ["inda", "lecio"],
        "Irineo": ["iri", "rineo"],
        "Isidro": ["isi", "sidro"],
        "Ivo": ["ivito", "ivón"],
        "Isaías": ["Isaí", "Saías"],
        "Jacky": ["jacki"],
        
        "Jacinto": ["cinto", "jacincito"],
        "Javier": ["javi", "javo"],
        "Jimena": ["jime", "mena"],
        "Joaquín": ["joaco", "quin"],
        "Jorge": ["jor", "georgie"],
        "José": ["pepe", "joselito"],
        "Josué": ["josu", "sue"],
        "Juan": ["juancito", "juancho", "juan"],
        "Juana": ["juana", "juanita"],
        "Julia": ["juli", "julita"],
        "Julio": ["julito", "julión"],
        "Justo": ["justito", "tito"],
        "Jeremías": ["jere", "mías"],
        "Jesús": ["jesu", "chus"],
        "Jonás": ["joni", "jonasito"],
        
        "Karen": ["kari", "karencita"],
        "Kevin": ["kev", "kevito"],
        "Karola": ["karola"],
        "Karol": ["karol"],
        
        "Laura": ["lauri", "laurita"],
        "Leonardo": ["leo", "leonardito"],
        "Leticia": ["leti", "letic"],
        "Lidia": ["lidi", "lidita"],
        "Liliana": ["lili", "lilianita"],
        "Lorena": ["lore", "lorenita"],
        "Lourdes": ["lourditas", "lulú"],
        "Lucía": ["luci", "lucita"],
        "Luis": ["lucho", "luisito"],
        "Luisa": ["lui", "luisita"],
        "Leandro": ["lean", "drito"],
        "Lionel": ["lion", "lio"],
        "Lisandro": ["lisan", "sandrito"],
        "Lázaro": ["laza", "zarito"],
        "Ludovico": ["ludo", "vico"],
        
        "Marco": ["marquito", "marcol"],
        "Margarita": ["marga", "margarit"],
        "María": ["marita", "mari"],
        "Marta": ["martita", "marti"],
        "Mauricio": ["mau", "mauris"],
        "Maximiliano": ["max", "maxi"],
        "Mercedes": ["meche", "merche"],
        "Mónica": ["moni", "moniquita"],
        "Mateo": ["mate", "teo"],
        "Matías": ["mati", "tías"],
        "Martín": ["tin", "martincito"],
        "Máximo": ["maxi", "max"],
        "Marcos": ["marquitos", "marcol"],
        "Manuel": ["manu", "manuelito"],
        "Mauro": ["mauri", "maurito"],
        "Mariano": ["marian", "riano"],
        "Miguel": ["migue", "miguelito"],
        "Marcelo": ["chelito", "marce"],
        
        "Nadia": ["nadi", "nadia"],
        "Natalia": ["nata", "talita"],
        "Nicolás": ["nico", "nicolasito"],
        "Noelia": ["noe", "noelita"],
        "Nora": ["norita", "nori"],
        
        "Octavio": ["octa", "tavio"],
        "Olga": ["olguita", "olgi"],
        "Óscar": ["oski", "oscarcito"],
        "Osvaldo": ["osva", "valdo"],
        
        "Pablo": ["pablito", "pablete"],
        "Patricia": ["patri", "paty"],
        "Patricio": ["pato", "patrio"],
        "Paula": ["pau", "paulita"],
        "Pedro": ["pedrito", "perico", "pedro"],
        "Pilar": ["pili", "pilarcita"],
        
        "Rafael": ["rafa", "rafaelito"],
        "Ramón": ["moncho", "ramoncito"],
        "Raquel": ["raque", "quel"],
        "Rebeca": ["rebe", "beca"],
        "Renata": ["ren", "nata"],
        "Ricardo": ["richi", "riky"],
        "Roberto": ["beto", "robert"],
        "Rodrigo": ["rodri", "ro"],
        "Rocío": ["ro", "roci"],
        "Rosa": ["rosi", "rosita"],
        "Rosario": ["charo", "chari"],
        "Rubén": ["rubencito", "rub"],
        "Renato": ["ren", "nato"],
        "Ramiro": ["rami", "ramirito"],
        "Raúl": ["raulito", "rau"],
        "Rogelio": ["roge", "rogel"],
        "Román": ["roman", "romancito"],
        "Rufino": ["rufi", "finito"],
        "Ruth": ["ruty", "ruti", "rut"],
        
        "Salvador": ["salva", "chava"],
        "Samuel": ["samu", "samuelito"],
        "Sandra": ["sandi", "sandrita"],
        "Santiago": ["santi", "yago"],
        "Sara": ["sarita", "sari"],
        "Sebastián": ["seba", "sebas"],
        "Serafín": ["sera", "fino"],
        "Sergio": ["serch", "sergito"],
        "Silvia": ["silvi", "silvita"],
        "Sofía": ["sofi", "sofis"],
        "Soledad": ["sole", "soled"],
        "Santino": ["santi", "santino"],
        "Silvio": ["silvi", "silvito"],
        "Saúl": ["saulito", "sauli"],
        "Santos": ["santitos", "santos"],
        "Samira": ["sami"],
        "Sunilda": ["suni", "suny", "sunil"],
        
        
        "Teresa": ["tere", "teresita"],
        "Timoteo": ["tim", "teo"],
        "Tomás": ["tomi", "tomasito"],
        "Trinidad": ["trini", "nidad"],
        "Thiago": ["tiago", "tiaguito"],
        "Teodoro": ["teo", "doro"],
        "Tadeo": ["tade", "tadito"],
        "Tobías": ["tobi", "bías", "tob"],
        "Tristán": ["tris", "triste"],
        "Toribio": ["tori", "bío"],
        "Tarsicio": ["tarso", "sicio"],
        "Telmo": ["tel", "telmito"],
        
        "Úrsula": ["ursi", "urula"],
        "Uriel": ["uri", "rielito"],
        "Urbano": ["urba", "bano"],
        "Ubaldo": ["uba", "baldo"],
        "Umberto": ["umber", "bertito"],
        "Uziel": ["uzi", "zielito"],
        "Ulrico": ["ulri", "ricito"],
        "Ursino": ["ursi", "sinito"],
        "Ulises": ["uli", "ulisesito"],
        "Ulfrido": ["ulfri", "frido"],
        
        "Valentín": ["valen", "valent"],
        "Víctor": ["viti", "victor"],
        "Vladimir": ["vladi", "mir"],
        "Valerio": ["vale", "lerio"],
        "Vasco": ["vasc", "vascu"],
        "Víctor Hugo": ["vitu", "huguito"],
        "Ventura": ["ventu", "turita"],
        "Virgilio": ["virgi", "gilio"],
        "Vito": ["vitito", "vitón"],
        "Valentina": ["valen", "valent"],
        "Valeria": ["vale", "valerita"],
        "Vanesa": ["vane", "vanesita", "vanessa"],
        "Verónica": ["vero", "verito"],
        "Vicente": ["vicho", "vicen"],
        "Victoria": ["vicky", "vic"],
        "Violeta": ["vio", "violet"],

        "Walter": ["walt", "waltito"],
        "Wendy": ["wen", "wendyta"],
        "Wilfredo": ["wil", "fredo"],
        "Waldemar": ["walde", "demar"],
        "Wenceslao": ["wen", "wencho"],
        "Winston": ["wins", "stoni"],
        "Wilson": ["wils", "soni"],
        "Wagner": ["wag", "gnerito"],
        "Warren": ["war", "rencito"],
        "Washington": ["wash", "toni"],
        
        "Ximena": ["xime", "mema"],
        "Xavier": ["xavi", "xavito"],
        "Xenón": ["xeno", "xenito"],
        "Xandro": ["xan", "drito"],
        "Xulian": ["xuli", "lian"],
        "Xerxes": ["xerx", "xerxito"],
        "Xabier": ["xabi", "bier"],
        "Xenio": ["xeni", "nito"],
        "Ximun": ["ximu", "mun"],
        "Xoel": ["xoe", "xoelito"],
        "Xurxo": ["xur", "xurxito"],
        
        "Yolanda": ["yoli", "yolandita"],
        "Yvette": ["yve", "yvettita"],
        "Yair": ["yai", "yairito"],
        "Yeray": ["yer", "rayito"],
        "Yamil": ["yami", "mil"],
        "Yonatan": ["yona", "tan"],
        "Yaco": ["yac", "yacito"],
        "Yerko": ["yerk", "yerkito"],
        "Yeferson": ["yefe", "son"],
        "Yuri": ["yuri", "yurito"],
        "Yeremías": ["yere", "mías"],
        
        "Zacarías": ["zaca", "zacar"],
        "Zoe": ["zo", "zoecita"]
        
    }
} as const;
